package com.omnia.pie.cm.services;

public enum JobTypeE {

	OFFLINE,
	ONLINE,
	INSTALL_NEW_ADS,
	INSTALL_APPLICATION,
	INSTALL_CONFIGURATION,
	INSTALL_PATCH,
	INSTALL_REGISTRY,
	RETRIEVE_CONFIGURATION,
	SHUTDOWN_MACHINE,
	RETRIEVE_EJ,
	RETRIEVE_LEADS,
	RETRIEVE_LOG,
	STOP_VTM_APP,
	START_VTM_APP,
	RETRIEVE_ANTI_SKIMMING,
	INITIALIZE_DEVICE,
	RESET_DEVICE
}
